server:
  port: 8089

spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: "auditlog-1"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'

  datasource:
    url: jdbc:postgresql://localhost:5435/auditlog
    username: auditlog
    password: auditlog
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: false
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true